### ISSUE TITLE
Is it ok to use a standard CSS stylesheet to style my elm app?

### ISSUE THREAD

**Issue by terezka** [terezka/elm-problem-dictionary#2]

**Comment by terezka** [comment]
Yes, that's totally ok! You can add ids and classes in your elm view and refer to those classes in your stylesheet.

```elm
view : Html msg
view =
  div 
    [ id "my-id" ] 
    [ div [ class "my-class" ] [ ... ] ]
```

```css
#my-id { background-color: green; }
.my-class { background-color: red; }
```
